services:
  backend:
    image: ${DOCKERHUB_USERNAME}/fullstack-backend:${TAG:-latest}
    build:
      context: .
      dockerfile: backend/Backend-Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}

  frontend:
    image: ${DOCKERHUB_USERNAME}/fullstack-frontend:${TAG:-latest}
    build:
      context: .
      dockerfile: frontend/Frontend-Dockerfile
    restart: unless-stopped
    ports:
      - "80:5050"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
      - VITE_INFLUX_URL=${VITE_INFLUX_URL}
