services:
  backend:
    image: ${DOCKERHUB_USERNAME}/fullstack-backend:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "5296:5296"
    environment:
      - INFLUX_URL=http://10.188.10.151:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}

  frontend:
    image: ${DOCKERHUB_USERNAME}/fullstack-frontend:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "80:80"

    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
      - VITE_INFLUX_URL=${VITE_INFLUX_URL}
